### ISSUE TITLE
Raw xml passthrough mode (no conversion to JSON)

### ISSUE THREAD

**Issue by Sporran** [gisikw/xml-loader#7]
Legacy platforms being integrated into Webpack often employ their own application-specific XML parsers (eg: for MusicXML).

For these, it makes no sense to convert imported XML to JSON. Any internal re-conversion (back to the original XML) would be inherently fragile and error prone.

Nevertheless, xml-loader **automatically** converts imported XML files to JSON, with **no means of prevention**.

For some other loaders, however, Webpack's Rule.type sets the type for a matching module, preventing defaultRules and their default importing behaviors from occurring.

I would like to see some form of raw xml passthrough enabled. I envisage something along the lines of an "xml/auto" Rule.type to ensure no conversion to JSON is undertaken.

Any such pass-through behavior should avoid provoking a "Module parse failed: Unexpected token" error. The attached MusicXML file has in the past been seen to provoke such an error.

To give an idea of the impact of this issue, until I can import raw XML files into webpack, my current project is blocked.

This problem is currently the subject of two open questions on stackoverflow:

- [55013135](https://stackoverflow.com/questions/55013135/imported-musicxml-error-using-xml-loader-or-raw-loader-d3-js-in-a-webpack-envi)
- [55054469](https://stackoverflow.com/questions/55054469/how-to-import-xml-using-a-webpack-loader-without-automatic-conversion-to-json)

[WAM_K458_1.zip](https://github.com/gisikw/xml-loader/files/2945766/WAM_K458_1.zip)

**Comment by gisikw** [comment]
Hiya,

I think there may be some confusion here. The whole premise of xml-loader *is* to parse xml to json. The file is loaded as a string, then parsed into a json structure. There is no intermediary step where an xml "structure" exists (JS doesn't have a native xml data structure, even if browsers may).

In cases where you want to parse the xml yourself, then this module shouldn't be used. You'd want to rely on raw-loader or similar to pull in your file as a string and pass that value around.

To remove the parsing step of xml-loader would be effectively the same as simply not using xml-loader at all. Looking at your SO issue, raw-loader is the correct solution to your specific issue.

If I'm misunderstanding your request, please let me know what you'd expect the imported value to be under your proposed use case.

**Comment by gisikw** [comment]
Just to expand on your SO issue, it seems your issue began with d3's `.xml` function not being able to accept raw strings instead of urls. It looks from their examples that they're creating a document (or at least something that implements `.querySelector`), so if we can presume a browser environment, how about bypassing d3's wrapper and creating a document directly (see https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) - so something like the following:

```js
import score from '!!raw-loader!./path-to-file.xml';

var parser = new DOMParser();
var doc = parser.parseFromString(score, "application/xml");

/// ...do assorted stuff with d3, now that doc is a DOM representing your score
```

**Comment by Sporran** [comment]
Hi, thanks for the rapid response.

I had already played around somewhat with DOMParser, and while I did get as far as to access the top level element in the xml document structure, DOMParser's mere presence appears to pollute Webpack's subsequent handling / interpretation of the final index.html file. Typically I'm rewarded with something along the lines of:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /[object%20XMLDocument]</pre>
</body>
</html>
```

Where I want to **parse** the xml file, Webpack seems to want to **serve it up** (as-is) in the browser... With the DOMParser approach both acknowledged (by d3.js's creator) and promising as an alternative to d3.xml(), it would be helpful to know if this unwanted behavior can be blocked..

Otherwise, the encoded values returned by DOMParser seem to be subtly different to those made available using the original d3.js v3 d3.xml() calls. DOMParser returns a string, d3.js v3's d3.xml() a document. They appear to be mutually incompatible.

To cut a long story short, I'm currently going through step by step comparing the values returned both by my original, freestanding d3.js v3 d3.xml() calls, and those returned by DOMParser in conjunction with imported d3.js v3 and v5 libraries.

Your suggestions are definitely helpful. Mine, perhaps less so. Namely: a loader **loads** (pass-through) and a parser **parses** (breaks data into it's component elements for translation).The naming of xml-loader is confusing, which, had it been possible, a Rule.type supporting direct pass-through may have alleviated..

For the meantime, however, I'm going with raw-loader.

**Comment by gisikw** [comment]
Hiya,

I think there's still some confusion here regarding how webpack and vanilla JS work. There is no concept of a "document" in JS itself - document structures (and DOMParser) exist solely in the browser (can think of it as a standard library automatically loaded by the browser). So at Webpack build time, there's no document structure available to be used.

Webpack's sole purpose is to deliver executable JS as output, and when dealing with CSS, XML, CSVs, images, etc, the loaders simply define how that content gets injected into the final built JS. Many of the loaders try to inject the content in a way that makes it easier to access and manipulate in JS. Loaders like raw-loader try to paste the contents in as a string.

So if we take some comma-separated value file as an example:

```js
// CSV contents
name,username,age
Kevin,gisikw,30

// index.js
import data from "data.csv";
```

Then we'll get different output depending on what loader we use. Roughly speaking, here's what that'll build to:

```js
// When using csv-loader
const data = [{name: "Kevin", username: "gisikw", age: 30}];

// When using raw-loader
const data = "name,username,age\nKevin,gisikw,30";
```

The XML loader operates in the same way - it reads XML and tries to serialize it in a way that it can be easily accessed for most use cases. This doesn't really fit what you're trying to do, so it's not really the right fit here. raw-loader best matches your particular use case. That will get you your XML embedded into the JS as a string. It's then incumbent upon your code to create a document (via the browser or d3's wrapper around browser utils) at runtime.

---

Regarding your point about semantics - I understand that the term **loader** can be confusing, however this is really a matter of convention. The more correct term (for *all* Webpack loaders) would probably be **reserializer**, since the goal of any Webpack loader is to take file contents as an input, and spit out JS as an output. Since there's no `document` in native JS, the concept of "loading" XML doesn't really make sense at all (in the same way that since there's no native `CSV` object, a csv-loader necessarily is going to have to generate a serialized representation of the CSV, not "the CSV itself")

If xml-loader were to be modified to prevent its current form of serialization, the result would simply be to take the file contents, and then reserialize them as a string. That's semantically not "avoiding parsing", it's just opting for a different serialization format. However, convention is "when you want the file contents as a JS string: use raw-loader". Making xml-loader optionally do that too would be redundant.

I'm going to go ahead and close this issue since I don't think it reflects a problem with `xml-loader` per se. Happy to continue the discussion though regarding your particular use case, or reopen it if we identify an issue with xml-loader itself.

Cheers!

**Comment by Sporran** [comment]
Issue closure is fine by me, and thanks for the exhaustive answers. As an integrator, this scenario is symptomatic of (my) breadth over depth knowledge.

BTW, I isolated those DOMParser side-effects in the final index.html simply by wrapping the code in an auto-executing function expression à la:

```
import score from '!!raw-loader!./path-to-file.xml';
(() => {
  // DOMParser stuff
})()
```
Perhaps I can now make progress on the parsing itself. :-)
